# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Home"
  url = "#about"
  weight = 10

[[main]]
  name = "Recent news"
  url = "#recent"
  weight = 20


[[main]]
  name = "Research"
  url = "research/"
  weight = 20

[[main]]
  name = "People"  # Title of the link.
  url = "people/"  # Widget Page folder name.
  weight = 30  # Position of the link in the navigation bar.

[[main]]
  name = "Publications"
  url = "publication/"
  weight = 40

[[main]]
  name = "Teaching"
  url = "courses/"
  weight = 50

[[main]]
  name = "Contact"
  url = "#contact/"
  weight = 60

[[main]]
  name = "Opportunities"
  url = "opps/"
  weight = 70

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
 [[main]]
    name = "CV"
    url = "files/cv.pdf"
    weight = 80